arm:
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint0
      - joint1
      - joint2

    gains:
      joint0: {p: 100.0, i: 0.0, d: 0.1}
      joint1: {p: 100.0, i: 0.0, d: 0.1}
      joint2: {p: 100.0, i: 0.0, d: 0.1}